name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

#    - name: Generate app APK.
#      run: ./gradlew assembleDebug --stacktrace
#
#    - name: Upload APK to Github Artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: merch_app.apk
#        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Generate app bundle
      run: ./gradlew app:bundleRelease --stacktrace

    - name: Sign app bundle
      run: |
        jarsigner -keystore keystore/Untitled \
        -storepass 'key_ci_cd'  -keypass 'key_ci_cd'  \
        app/build/outputs/bundle/release/app-release.aab 'key02'
          
