name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  setup-jdk:
    runs-on: ubuntu-latest

  linux-commands:
  
    runs-on: ubuntu-latest
    
    steps:
      - run: expl 1+1 > out.log
      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
      
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file
