name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  linux-commands:
  
    runs-on: ubuntu-latest
    
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
      
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file
